# Generated by Django 6.0 on 2026-08-20 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(max_length=200, unique=True, verbose_name='Title')),
                ('category', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')])),
                ('type', models.CharField(choices=[('normal', 'Normal'), ('urgent', 'Urgent')])),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='description')),
                ('is_complete', models.BooleanField(default=False)),
                ('Created_At', models.DateField(auto_now_add=True, verbose_name='Is_created_at')),
                ('Updated_At', models.DateTimeField(auto_now=True, verbose_name='Updated_At')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Scheduled_at')),
            ],
        ),
    ]
