# Generated by Django 6.0 on 2026-08-20 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0002_alter_task_category_alter_task_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(blank=True, max_length=600, verbose_name='description'),
        ),
    ]
