# Generated by Django 6.0 on 2026-08-21 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0004_alter_task_description_alter_task_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='description',
        ),
    ]
