# Generated by Django 6.0 on 2026-08-21 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0005_remove_task_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='Created_At',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Is_created_at'),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Scheduled_at'),
        ),
    ]
