# Generated by Django 6.1 on 2026-09-20 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0010_user_alter_task_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
    ]
